# Generated by Django 4.1 on 2022-09-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('details', models.CharField(blank=True, max_length=120, null=True)),
                ('gradegrp', models.CharField(blank=True, max_length=120, null=True)),
                ('misc', models.CharField(blank=True, max_length=120, null=True)),
                ('recovery', models.CharField(blank=True, max_length=120, null=True)),
                ('typeo', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.FloatField(blank=True, default=0, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grade_quality', to='myapp.grade')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_quality', to='myapp.supplier')),
                ('yard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Yard_quality', to='myapp.yard')),
            ],
        ),
        migrations.CreateModel(
            name='GradeOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grade_gradeoverhead', to='myapp.grade')),
            ],
        ),
        migrations.CreateModel(
            name='GradeMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('cost', models.CharField(blank=True, max_length=120, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grade_grademetal', to='myapp.grade')),
            ],
        ),
    ]
