# Generated by Django 4.1 on 2022-09-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_grade_quality_gradeoverhead_grademetal'),
    ]

    operations = [
        migrations.AddField(
            model_name='grademetal',
            name='metal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metal_grademetal', to='myapp.metal'),
        ),
        migrations.AddField(
            model_name='gradeoverhead',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_gradeoverhead', to='myapp.cost'),
        ),
    ]
