# Generated by Django 4.1 on 2022-09-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_grademetal_metal_gradeoverhead_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.FloatField(blank=True, default=0, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grade_actual', to='myapp.grade')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_actual', to='myapp.supplier')),
                ('yard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Yard_actual', to='myapp.yard')),
            ],
        ),
        migrations.RemoveField(
            model_name='grademetal',
            name='name',
        ),
        migrations.AddField(
            model_name='gradeoverhead',
            name='cost_value',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='QualityOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_value', models.CharField(blank=True, max_length=120, null=True)),
                ('cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_Qualityoverhead', to='myapp.cost')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_Qualityoverhead', to='myapp.quality')),
            ],
        ),
        migrations.CreateModel(
            name='QualityMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(blank=True, max_length=120, null=True)),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metal_Qualitymetal', to='myapp.metal')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_Qualitymetal', to='myapp.quality')),
            ],
        ),
        migrations.CreateModel(
            name='ActualOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_value', models.CharField(blank=True, max_length=120, null=True)),
                ('actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actual_Actualoverhead', to='myapp.actual')),
                ('cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_Actualoverhead', to='myapp.cost')),
            ],
        ),
        migrations.CreateModel(
            name='ActualMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(blank=True, max_length=120, null=True)),
                ('actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actual_Actualmetal', to='myapp.actual')),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metal_Actualmetal', to='myapp.metal')),
            ],
        ),
    ]
