# Generated by Django 4.1 on 2022-09-09 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_actualmetal_actual_value_actualmetal_weightage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual',
            name='grade',
        ),
        migrations.AddField(
            model_name='actual',
            name='qualitys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grade_actual', to='myapp.quality'),
        ),
    ]
