# Generated by Django 4.1 on 2022-09-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_gradenewvalue_remove_actualmetal_po_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual',
            name='qualitys',
        ),
    ]
