# Generated by Django 4.1 on 2022-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_actual_qualitys'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='recovery',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='typeo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
