# Generated by Django 4.1 on 2022-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_quality_recovery_quality_typeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='alc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='mc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='ohc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
