# Generated by Django 4.1 on 2022-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_quality_alc_quality_mc_quality_ohc'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='weightage_al',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
