# Generated by Django 4.1 on 2022-09-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_quality_weightage_al'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grade_actual', to='myapp.grade'),
        ),
    ]
