# Generated by Django 4.1 on 2022-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_actual_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual',
            name='alc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='actual',
            name='mc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='actual',
            name='ohc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='actual',
            name='weightage_al',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
